Livraria Lunar E-commerce/Controllers/PerfilController.cs
using Livraria_Lunar_E_commerce.Business;
using Livraria_Lunar_E_commerce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Livraria_Lunar_E_commerce.Controllers
{
    public class PerfilController : Controller
    {
        // GET: Perfil
        public ActionResult Index(int id)
        {

            ClientesAcoes acCliente = new ClientesAcoes();
            return View(acCliente.ConsultaPerfil(id).Find(dto => dto.cd_cliente == id));
        }

        [HttpPost]
        public ActionResult Index(Cliente dto)
        {
            if (ModelState.IsValid)
            {
                ClientesAcoes acCliente = new ClientesAcoes();
                acCliente.Alterar(dto);
            }
            
            return View();
        }


        public ActionResult Pedidos(int id)
        {
            PedidoAcoes acPedidos = new PedidoAcoes();
            return View(acPedidos.Consultar(id));
        }
    }
}

Livraria Lunar E-commerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Livraria Lunar</title>
    <link rel="apple-touch-icon" sizes="180x180" href="~/Content/assets/images/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/assets/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/assets/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link href="~/Content/scss/estilo.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap"
          rel="stylesheet">

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
</head>
<body style="background-color: #F5F5F5 !important">
    <div class="d-flex flex-column wrapper">
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-primary">
                <div class="container p-md-0">
                    <a class="navbar-brand" href="/Home/Index">
                        <img src="~/Content/assets/images/Logosemcor.png" alt="Logo" class="img-fluid" />
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse menu justify-content-end align-items-center p-0" id="navbarSupportedContent">
                        <ul class="navbar-nav">
                            <form action="/Home/ConsultaporNome" method="post" class="d-flex search-bar">
                                <input class="form-control search" type="text" placeholder="Pesquise o produto" id="produto" name="produto" >
                                <button class="btn-search" type="submit" id="produto" name="produto" ><i class="bi bi-search"></i></button>
                            </form>
                            
                            @if (Session["tipoLogado1"] != null || Session["tipoLogado2"] != null || Session["tipoLogado3"] != null || Session["usuarioLogado"] != null)
                            {
                        <li class="nav-item" style="max-width:9rem; overflow:hidden; text-overflow:ellipsis; white-space:nowrap">
                            <a class="nav-link" style="max-width:9rem; overflow:hidden; text-overflow:ellipsis; white-space:nowrap" title="@Session["usuarioLogado"].ToString()" href="@Url.Action("Index" ,"Perfil", new {  id= Session["cd_cliente"]  })">@Session["usuarioLogado"].ToString()<i class="bi bi-person-plus"></i></a>
                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="/Login/Logout">Logout <i class="bi bi-box-arrow-left"></i></a>
                                        </li>
 }
                                    else
                                    {
                        <li class="nav-item">
                            <a class="nav-link" href="/Home/Cadastrar">Crie sua conta <i class="bi bi-person-plus"></i></a>
                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="/Login/Login">Entre <i class="bi bi-box-arrow-in-right"></i></a>
                                        </li>}
                            <li class="nav-item">
                                <a class="nav-link" href="/Home/Carrinho">Carrinho <i class="bi bi-cart2"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>




        <div class="flex-fill mb-3">
            @RenderBody()
        </div>


        <footer class="border-top text-muted bg-light mt-2 p-3">
            <div class="container">
                <div class="row">
                    <div class="col-4 text-center text-muted">
                        &copy; 2021 - Livraria Lunar <br />
                        Rua Guaipá, 678 - Vila Leopoldina, São Paulo - SP, 05089-000 <br />
                        CNPJ 99.999.999/0001-99
                    </div>
                    <div class="col-4 text-center d-flex flex-column">
                        <a href="" class="text-decoration-none text-dark">Politica de privacidade</a>
                        <a href="" class="text-decoration-none text-dark">Termos de Uso</a>
                        <a href="" class="text-decoration-none text-dark">Quem somos</a>
                        <a href="" class="text-decoration-none text-dark">Trocas e Devoluções</a>
                    </div>
                    <div class="col-4 text-center d-flex flex-column">
                        <a href="" class="text-decoration-none text-dark">Telefone (11) 3834-4111</a>
                        <a href="" class="text-decoration-none text-dark">Perguntas Frequentes</a>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/Content/assets/js/bootstrap.bundle.min.js"></script>

    @Scripts.Render("~/bundles/jquery")
    <script src="~/Content/assets/js/cep.js"></script>

    <script>
        $(document).ready(function () {
            $("#cpf").inputmask("mask", { "mask": "999.999.999-99" }, { reverse: true });
            $("#celular").inputmask("mask", { "mask": "(99) 9999-99999" });
            $("#telefone").inputmask("mask", { "mask": "9999-9999" });
            $('.date').mask('00/00/0000');
            $('.vl_unitario').mask('000.000.000.000.000,00', { reverse: true });
        });



    </script>

    @Scripts.Render("~/bundles/inputmask")

    @RenderSection("scripts", required: false)
</body>
</html>

Livraria Lunar E-commerce/Views/Shared/_carousel.cshtml
<div class="container mt-2 " style="min-height:200px">
    <div id="carouselMain" class="carousel slide" data-bs-ride="carousel">

        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Content/assets/images/slide1.jpg" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/Content/assets/images/slide2.jpg" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselMain" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
            <span class="visually-hidden">Anterior</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselMain" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
            <span class="visually-hidden">Próximo</span>
        </button>
    </div>
</div>